In [3]:
import pandas as pd
df = pd.read_csv("data/A_message_delivery.csv")

In [4]:
df.isna().sum()

message_id              0
campaign_id             0
account_id              0
sender_name             0
recipient_id          252
network_provider      586
sent_at                 0
delivered_at         2595
delivery_status         0
error_code          27705
message_parts           0
cost                    0
dtype: int64

In [5]:
df[pd.isnull(df.recipient_id)]

,message_id,campaign_id,account_id,sender_name,recipient_id,network_provider,sent_at,delivered_at,delivery_status,error_code,message_parts,cost
34,MSG00024783,CMP022,ACC0100,Sender_06,NaN,Provider_C,2026-05-11 05:13:09,2026-05-11 05:14:35,delivered,NaN,1,22.74
117,MSG00029755,CMP038,ACC0192,Sender_07,NaN,Provider_A,2026-05-31 12:45:42,2026-05-31 12:46:21,delivered,NaN,1,22.33
371,MSG00017991,CMP025,ACC0078,Sender_05,NaN,Provider_A,2026-04-28 11:26:32,2026-04-28 11:28:01,delivered,NaN,1,29.48
685,MSG00012781,CMP007,ACC0046,Sender_05,NaN,Provider_A,2026-05-21 12:54:47,2026-05-21 12:55:27,delivered,NaN,2,42.35
770,MSG00021250,CMP015,ACC0142,Sender_04,NaN,Provider_B,2026-05-11 09:02:04,2026-05-11 09:02:08,delivered,NaN,1,20.82
...,...,...,...,...,...,...,...,...,...,...,...,...
30079,MSG00007925,CMP045,ACC0100,Sender_07,NaN,Provider_B,2026-05-10 10:45:28,2026-05-10 10:46:10,delivered,NaN,1,23.62
30105,MSG00015934,CMP003,ACC0043,Sender_07,NaN,Provider_A,2026-04-04 13:22:19,2026-04-04 13:23:47,delivered,NaN,3,60.57
30147,MSG00017543,CMP036,ACC0194,Sender_01,NaN,Provider_A,2026-05-11 14:35:37+08:00,2026-05-11 14:36:52,delivered,NaN,1,28.76
30159,MSG00019164,CMP045,ACC0045,Sender_06,NaN,Provider_D,2026-05-27 13:34:37,2026-05-27 13:35:09,delivered,NaN,1,29.93
30254,MSG00004655,CMP010,ACC0033,Sender_02,NaN,Provider_A,2026-05-04 14:49:08+08:00,2026-05-04 14:49:57,delivered,NaN,2,49.72

In [7]:
miss = df.recipient_id.isnull().sum()

In [8]:
print(miss)

252

In [9]:
miss = df.delivery_status.isnull().sum()
print(miss)

0

In [10]:
miss = df.error_code.isnull().sum()
print(miss)

27705

In [11]:
miss = df[df.recipient_id.isnull()]
print(len(miss))

252

In [12]:
df.head()

,message_id,campaign_id,account_id,sender_name,recipient_id,network_provider,sent_at,delivered_at,delivery_status,error_code,message_parts,cost
0,MSG00017303,CMP027,ACC0135,Sender_06,9XXXXX62,NaN,2026-05-18 11:23:42,2026-05-18 11:25:02,delivered,NaN,2,50.95
1,MSG00012498,CMP029,ACC0183,Sender_02,9XXXXX30,Provider_B,2026-05-08 07:10:19,2026-05-08 07:10:33,delivered,NaN,2,46.18
2,MSG00021899,CMP040,ACC0172,Sender_02,9XXXXX84,Provider_B,2026-04-21 00:17:03,2026-04-21 00:17:54,delivered,NaN,2,57.09
3,MSG00028690,CMP020,ACC0095,Sender_06,9XXXXX97,Provider_A,2026-05-06 08:42:41,2026-05-06 08:43:18,delivered,NaN,1,25.09
4,MSG00014531,CMP049,ACC0155,Sender_04,9XXXXX76,Provider_C,2026-04-21 07:52:00,2026-04-21 07:53:03,delivered,NaN,1,27.90

In [13]:
df.isna().sum()

message_id              0
campaign_id             0
account_id              0
sender_name             0
recipient_id          252
network_provider      586
sent_at                 0
delivered_at         2595
delivery_status         0
error_code          27705
message_parts           0
cost                    0
dtype: int64

In [21]:
df['recipient_id'] = df.recipient_id.fillna("Unknown")

In [22]:
df.isna().sum()

message_id              0
campaign_id             0
account_id              0
sender_name             0
recipient_id            0
network_provider      586
sent_at                 0
delivered_at         2595
delivery_status         0
error_code          27705
message_parts           0
cost                    0
dtype: int64

In [23]:
df['network_provider'] = df.network_provider.fillna("Unknown Provider")

In [24]:
df.isna().sum()

message_id              0
campaign_id             0
account_id              0
sender_name             0
recipient_id            0
network_provider        0
sent_at                 0
delivered_at         2595
delivery_status         0
error_code          27705
message_parts           0
cost                    0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(300)

In [26]:
df = df.drop_duplicates()

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
df["sent_at"] = pd.to_datetime(df["sent_at"], errors="coerce", utc="True" , format="mixed")
print("NaT (bad dates):" , df["sent_at"].isna().sum())

NaT (bad dates): 0

In [29]:
df.message_parts.max()

np.int64(90)

In [32]:
df.message_parts.value_counts()

message_parts
1     21014
2      6589
3      2112
87       11
50       11
42        9
75        9
76        9
52        8
83        8
62        8
70        8
64        8
45        8
40        7
54        7
69        7
53        7
55        7
48        7
74        7
58        6
63        6
43        6
89        6
73        6
79        6
78        6
46        5
51        5
81        5
71        5
85        5
61        5
44        5
59        5
47        4
82        4
80        4
41        4
77        4
65        4
60        4
67        3
68        3
56        3
72        3
90        3
86        3
84        3
88        3
49        2
57        2
66        1
Name: count, dtype: int64

In [33]:
df.message_parts.sort_values(ascending=False).head(10)

11302    90
2238     90
22773    90
2622     89
10764    89
26246    89
21519    89
29410    89
27890    89
13925    88
Name: message_parts, dtype: int64

In [35]:
import numpy as np
df['message_parts'] = np.where(df['message_parts'] > 3, np.nan, df['message_parts'])

In [36]:
df.message_parts.value_counts()

message_parts
1.0    21014
2.0     6589
3.0     2112
Name: count, dtype: int64

In [38]:
miss = df.message_parts.isnull().sum()
print(miss)

285

In [39]:
df.cost.max()

np.float64(4141.5)

In [40]:
df.cost.value_counts()

cost
27.03      36
27.27      35
20.13      35
29.94      35
27.87      35
           ..
76.25       1
1651.53     1
47.19       1
64.20       1
88.06       1
Name: count, Length: 4804, dtype: int64

In [43]:
df.cost.sort_values(ascending=False).head(50)

9698     4141.50
3908     2711.00
21435    2699.00
11302    2686.70
2238     2650.40
8623     2587.68
6205     2558.00
29350    2529.29
10764    2529.11
22773    2528.99
27941    2526.50
29410    2524.33
13750    2489.79
9355     2463.74
23644    2437.74
13277    2432.92
29277    2413.86
3418     2407.50
18067    2385.59
25655    2359.36
14269    2351.93
18084    2347.36
4942     2320.98
21519    2298.93
21687    2294.64
3172     2293.50
14629    2291.34
27890    2288.08
16469    2270.42
2449     2253.27
7613     2248.48
3055     2245.17
11159    2242.64
29003    2225.03
14443    2217.66
11086    2216.94
14737    2206.14
12220    2203.28
22474    2201.96
19293    2186.60
21234    2178.98
26873    2165.36
15603    2158.45
14297    2155.21
25679    2146.59
3457     2129.86
28883    2123.28
29049    2116.87
24470    2108.74
15808    2106.14
Name: cost, dtype: float64

In [44]:
df.cost.min()

np.float64(-70.29)

In [45]:
df.cost.sort_values().head(50)

29276   -70.29
16884   -63.62
23149   -58.42
23156   -54.80
24684   -51.63
2344    -49.51
24532   -29.96
8374    -28.53
22511   -27.46
5963    -27.33
9198    -27.26
10804   -25.55
20326   -25.03
553     -24.94
23408   -24.78
23783   -24.38
3550    -23.52
28153   -23.25
12580   -23.21
7491    -22.59
14290   -22.51
19890   -22.39
5108    -21.72
14442   -21.07
7126    -20.68
12744   -20.65
28241    20.00
18684    20.00
8552     20.00
24274    20.00
15011    20.00
27053    20.00
13970    20.00
4971     20.00
17316    20.00
24594    20.00
6752     20.00
29485    20.00
28200    20.01
5327     20.01
26107    20.01
21950    20.01
9081     20.01
329      20.01
10836    20.01
26811    20.01
22593    20.01
19087    20.01
14761    20.01
11240    20.01
Name: cost, dtype: float64

In [50]:
df['cost'] = np.where(df['cost'] < 0, np.nan, df['cost'])

In [52]:
df.cost.sort_values().head(20)

15011    20.00
29485    20.00
18684    20.00
24274    20.00
17316    20.00
8552     20.00
28241    20.00
6752     20.00
13970    20.00
24594    20.00
27053    20.00
4971     20.00
11240    20.01
9081     20.01
14199    20.01
18079    20.01
27868    20.01
9065     20.01
329      20.01
23215    20.01
Name: cost, dtype: float64

In [53]:
df['cost'] = np.where(df['message_parts'].isna(), np.nan, df['cost'])

In [55]:
df.cost.sort_values(ascending=False).head(20)

9698     4141.5
3908     2711.0
21435    2699.0
6205     2558.0
27941    2526.5
3418     2407.5
3172     2293.5
20068    2089.0
9051     2065.0
24070    1495.0
5841     1468.0
15185    1456.5
9500     1453.0
7301     1452.0
21921    1397.5
9284     1383.5
26544    1374.0
7452     1372.0
29923    1299.5
6349     1241.0
Name: cost, dtype: float64

In [56]:
df.isna().sum()

message_id              0
campaign_id             0
account_id              0
sender_name             0
recipient_id            0
network_provider        0
sent_at                 0
delivered_at         2566
delivery_status         0
error_code          27434
message_parts         285
cost                  311
dtype: int64

In [58]:
df[df['cost'] == 4141.5]

,message_id,campaign_id,account_id,sender_name,recipient_id,network_provider,sent_at,delivered_at,delivery_status,error_code,message_parts,cost
9698,MSG00001493,CMP045,ACC0079,Sender_01,9XXXXX97,Provider_D,2026-05-06 09:07:08+00:00,NaN,expired,E500,3.0,4141.5

In [59]:
df[df['cost'] == 2711.0]

,message_id,campaign_id,account_id,sender_name,recipient_id,network_provider,sent_at,delivered_at,delivery_status,error_code,message_parts,cost
3908,MSG00001276,CMP020,ACC0140,Sender_06,9XXXXX39,Provider_A,2026-04-25 00:19:31+00:00,2026-04-25 00:19:33,delivered,NaN,2.0,2711.0

In [60]:
df[df['cost'] == 2699.0]

,message_id,campaign_id,account_id,sender_name,recipient_id,network_provider,sent_at,delivered_at,delivery_status,error_code,message_parts,cost
21435,MSG00003043,CMP035,ACC0102,Sender_07,9XXXXX19,Provider_B,2026-05-24 08:04:27+00:00,2026-05-24 08:04:29,delivered,NaN,2.0,2699.0

In [62]:
df['cost'] = np.where(df['cost']==4141.5, np.nan, df['cost'])

In [63]:
df.cost.sort_values(ascending=False).head(10)

3908     2711.0
21435    2699.0
6205     2558.0
27941    2526.5
3418     2407.5
3172     2293.5
20068    2089.0
9051     2065.0
24070    1495.0
5841     1468.0
Name: cost, dtype: float64

In [65]:
df.to_csv("clean.csv", index=False)